### ISSUE TITLE
Catch exception when loading model: [Errno 20] Not a directory: './model/qwen2.5-3b-instruct-q4_k_m.gguf/config.json' Load model failed!

### ISSUE THREAD

**Issue by wangyong5123** [airockchip/rknn-llm#131]
$ python test.py 
INFO: rkllm-toolkit version: 1.1.2
ERROR: Catch exception when loading model: [Errno 20] Not a directory: './model/qwen2.5-3b-instruct-q4_k_m.gguf/config.json'
Load model failed!

加载的模型
modelpath = './model/qwen2.5-3b-instruct-q4_k_m.gguf'

提示目录不存在，并且还需要config.json？

这是为什么呢？

**Comment by c0zaut** [comment]
It looks like maybe you're using load_huggingface instead of load_gguf.? If you use load_huggingface, then the script looks for the .safetensors (or other pytorch) model in a folder, along with the configuration files for vocab, the tokenizer, etc. GGUF is a unified format, so all of that stuff is actually contained within the GGUF file itself, so it only takes a filename as an argument. 

Try the interactive version of my script: https://github.com/c0zaut/ez-er-rkllm-toolkit/tree/5d752cfa008071cc1f50a43dbe06e28b65ae5312/docker-interactive

Bear in mind, though, that only RK3576 supports 4-bit quants, so it might fail for the RK3588 platform. I also have a ready-to-go 1.1.1 conversion of Qwen 2.5 3B if you just want to try that out: https://huggingface.co/c01zaut/Qwen2.5-3B-Instruct-rk3588-1.1.1 It works with the 1.1.2 library. I have also a complete chat interface that I made with Gradio here: https://github.com/c0zaut/RKLLM-Gradio

Clone the Gradio repo, download the desired Qwen model and place it in the repo's models/ directory, and then update the filename in model_configs.py under the Qwen 2.5 section. Hope that helps!

**Comment by wangyong5123** [comment]
> @wangyong5123
> 
> It looks like maybe you're using load_huggingface instead of load_gguf? If you use load_huggingface, then the script looks for the .safetensors (or other pytorch) model in a folder, along with the configuration files for vocab, the tokenizer, etc. GGUF is a unified format, so all of that stuff is actually contained within the GGUF file itself, so it only takes a filename as an argument.
> 
> Try the interactive version of my script: https://github.com/c0zaut/ez-er-rkllm-toolkit/tree/5d752cfa008071cc1f50a43dbe06e28b65ae5312/docker-interactive
> 
> Bear in mind, though, that only RK3576 supports 4-bit quants, so it might fail for the RK3588 platform. I also have a ready-to-go 1.1.1 conversion of Qwen 2.5 3B if you just want to try that out: https://huggingface.co/c01zaut/Qwen2.5-3B-Instruct-rk3588-1.1.1 It works with the 1.1.2 library. I have also a complete chat interface that I made with Gradio here: https://github.com/c0zaut/RKLLM-Gradio
> 
> Clone the Gradio repo, download the desired Qwen model and place it in the repo's models/ directory, and then update the filename in model_configs.py under the Qwen 2.5 section. Hope that helps!


谢谢，问题已解决
