### ISSUE TITLE
Qwen2.5-14B 模型转换报错

### ISSUE THREAD

**Issue by yuguolong** [airockchip/rknn-llm#146]
转换模型：Qwen2.5-14B-Instruct-AWQ
运行报错信息：
(RKLLM-Toolkit) yugl@aigp-tnt:~/rknn-llm/rkllm-toolkit/examples$ python test.py
INFO: rkllm-toolkit version: 1.1.4
ERROR: Catch exception when loading model: 'sym'
Load model failed!

请问项目目前支持 Qwen 14B的模型吗？

**Comment by c0zaut** [comment]
It does, but you may be running out of memory, or the AWQ quant is not compatible. If you want to test out a Qwen 2.5 14B model, try this one that is preconverted: https://huggingface.co/imkebe/Qwen2.5-Coder-14B-Instruct-rk3588-1.1.4

I also have some that were requested by the same user for me to convert: 
https://huggingface.co/c01zaut/Virtuoso-Small-rk3588-1.1.4
https://huggingface.co/c01zaut/SuperNova-Medius-rk3588-1.1.4

All of the above are based on Qwen 2.5 14B. Please note that you will need a 32GB RAM board, since the IOMMU does not support swap for loading models (it does work for extending context, though, since even 4k is pretty bulky.)

**Comment by yuguolong** [comment]
@c0zaut Thanks for your answer, you did a great job, but I am using rk3576, the converted model may not run. My rk3576 has 16G memory, can it run the 14B model?

**Comment by c0zaut** [comment]
@yuguolong - Most likely not - the 14B model is exactly 16GB, so you will probably get OOM'd. 

I will try to update my conversion repo with the latest toolkit version, so you can test, though. The quantization is a little different on the RK3576, 4-bit weights and 16-bit attention. 

If you want to play around with my conversion script right now, you'll need to update the Dockerfiles and wheels to use the latest version, but most of the boiler plate is done, at least: https://github.com/c0zaut/ez-er-rkllm-toolkit

**Comment by yuguolong** [comment]
@c0zaut Thank you for your work.
