### ISSUE TITLE
Phi-2 Model Load Error

### ISSUE THREAD

**Issue by fydeos-alex** [airockchip/rknn-llm#2]
I got the 'PhiConfig' object has no attribute 'n_embd', what should I do?

I am trying to load it from huggingface and convert the trained model into an RKLLM format model, but the error occurred. I think it might caused by the update, can anyone tell me the version of phi-2 without this update?

THx🙏

**Comment by lzz773751548** [comment]
Yes, you're correct. The issue you're encountering is likely due to a recent update in the phi-2 model configuration that removed or altered the n_embd attribute. To resolve this, I recommend using the phi-2 model version associated with the specific commit mentioned below. This version does not include the recent changes that are causing the error you're experiencing.
https://hf-mirror.com/microsoft/phi-2/tree/834565c23f9b28b96ccbeabe614dd906b6db551a

**Comment by lzz773751548** [comment]
Yes, you're correct. The issue you're encountering is likely due to a recent update in the phi-2 model configuration that removed or altered the n_embd attribute. To resolve this, I recommend using the phi-2 model version associated with the specific commit mentioned below. This version does not include the recent changes that are causing the error you're experiencing.
https://hf-mirror.com/microsoft/phi-2/tree/834565c23f9b28b96ccbeabe614dd906b6db551a

**Comment by fydeos-alex** [comment]
I truly appreciate your help. Thank you so much.
