### ISSUE TITLE
Consider Open-Sourcing the Code After Nearly Two Months Without Updates 项目近两个月未更新，建议开源代码

### ISSUE THREAD

**Issue by AndySze** [airockchip/rknn-llm#74]
First, thank you for your significant contributions.
首先，感谢你们的巨大贡献。

The field of large language models is advancing rapidly, and even a week's delay can lead to obsolescence. This project has not been updated for nearly two months. Highly recommend open-sourcing the code to allow the community to contribute by adding new features and fixing bugs.
大语言模型领域发展迅速，甚至一周的延迟都会导致落后。这个项目已经近两个月没有更新了。强烈建议开源代码，让社区能够帮助添加新功能和修复漏洞。

**Comment by av1d** [comment]
I agree. The device is limited because of closed source, we are not able to develop it properly to its full potential.

**Comment by Pelochus** [comment]
Totally agree with this, without open sourcing we are truly limited. It would be wise to at least open source parts of it with proper documentation if possible

**Comment by Basicname** [comment]
I agree. Hope the amazing project be opened ASAP.

**Comment by 80Builder80** [comment]
Agreed 100%!!! Open-source this so we can utilize the chip to it's potential. Instead we are stuck waiting while LLM's are advancing everyday. By the time we get a working code, the potential will be lost. Other major players open-source their software because they know the community will improve the product and increase sales of their hardware. The sales pages out their for this chip push it's LLM support that is non-existent. Let the community improve the software and in return, you'll make more hardware sales. Good support = Happy Customers.

**Comment by lzd19981105** [comment]
同意！！！

**Comment by suranyami** [comment]
The code needs:

- Better maintenance: some of the binaries date back 5 years.
- Compatibility updates:
  - The restriction of only running the toolkit for conversion on `x86_64` is crazy and limiting.
  - Newer LLM models (e.g. llama3, llama3.1) don't convert at all. There are plenty of developers that would love debug the issues, but without the source code, it's impossible.
- User-space and Kernel-space drivers that cover all functionality. Developers are REVERSE-ENGINEERING the NPU, in order to deliver better, open-source alternative drivers. Why split efforts, when so much more could be done for completeness?

**Comment by happyme531** [comment]
https://github.com/ggerganov/llama.cpp/issues/722#issuecomment-2275488079

New evidence suggests that rkllm is a heavily modified and closed-source fork of llama.cpp. Instead of maintaining this closed branch by yourself, you might as well open-source the code. There’s a chance it could be merged upstream, which would give llama.cpp a decent NPU backend, immediate support for new models and multimodal models, and have community members fix bugs and optimize performance. Seriously, with a good community in place, why would you pay employees to maintain this branch, only to end up with slow updates, limited features, numerous bugs, and poor performance?

新的证据表明rkllm就是一个魔改且闭源的llama.cpp的fork。与其自己维护这个闭源分支，你不如把代码开源出来，没准可以合并到上游，这样llama.cpp就会有一个不错的npu后端，新的模型和多模态模型都能第一时间得到支持，并且会有社区成员修复bug并优化性能。说真的，既然有不错的社区，你为什么还要给员工发工资让他们自己维护这个分支，结果还更新缓慢，功能受限，bug多，性能低下呢？

**Comment by marty1885** [comment]
I'm open to contract and hiring... :-) Hope Rockchip can make the right call.

I mean, I'm in contact and waiting for the open source driver to release their documents. So a proper OSS  backend will happen eventually.

**Comment by danielmerja** [comment]
been a big fan of @marty1885 work and thank you for maintaining the project. Rockchip should open-source at this point. The community is patently waiting.

So far this guy Tomeu has tried to reverse engineer as well the NPU.

https://blog.tomeuvizoso.net/2024/06/rockchip-npu-update-4-kernel-driver-for.html

**Comment by vincenzodentamaro** [comment]
Opensource it, so it could jump to the next level. Having it closed source will prevent ot to be adopted as a standard. Your business is selling devices, isn't it?

**Comment by piwi3910** [comment]
Zero response or interaction with the community. I'm beginning to doubt to buy my 8 Orange pi 5 plus 32GB for LLM

**Comment by danielmerja** [comment]
People are frustrated and even the biggest contributor Joshua is frustrated with lack of support or communication from Rockchip.

https://github.com/Joshua-Riek/ubuntu-rockchip/discussions/1104

**Comment by peterwillcn** [comment]
@will.yang any news?

**Comment by Tang-JingWei** [comment]
赞同

**Comment by peterwillcn** [comment]
RockChip is not open source, I have no interest at all. Don't play RockChip, Come play[ Nvidia Jetson Orin Nano](https://www.youtube.com/watch?v=fcGD7kHgxqE) SUPER Is A Powerful Edge Ai NANO SBC!
![Screenshot 2024-12-24 at 13 53 43](https://github.com/user-attachments/assets/5736d5e6-3d9d-4d13-9c48-1bc45ca8f347)
